<a href="https://colab.research.google.com/github/DhimanTarafdar/perceptron-from-scratch/blob/main/Simple_Perceptron_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

## Perceptron Class Definition

In [2]:
class Perceptron:
  def __init__(self, eta, epochs):
    self.weights = np.random.randn(3) * 1e-4
    print(f"self.weights: {self.weights}")
    self.eta = eta
    self.epochs = epochs

  def activationFunction(self, inputs, weights):
    z = np.dot(inputs, weights)
    return np.where(z > 0 , 1, 0)

  def fit(self, X, y):
    self.X = X
    self.y = y

    X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))] # concactination
    print(f"X_with_bias: \n{X_with_bias}")

    for epoch in range(self.epochs):
      print(f"for epoch: {epoch}")
      y_hat = self.activationFunction(X_with_bias, self.weights)
      print(f"predicted value: \n{y_hat}")
      error = self.y - y_hat
      print(f"error: \n{error}")
      self.weights = self.weights + self.eta * np.dot(X_with_bias.T, error)
      print(f"updated weights: \n{self.weights}")
      print("#############\n")

  def predict(self, X):
    X_with_bias = np.c_[X, -np.ones((len(self.X), 1))]
    return self.activationFunction(X_with_bias, self.weights)

## Create Dataset for AND Gate

In [3]:
data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,0,0,1]}

AND = pd.DataFrame(data)
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [4]:
X = AND.drop("y", axis=1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [5]:
y = AND['y']
y.to_frame()

y
0  0
1  0
2  0
3  1

## Model Training (AND Gate)

In [6]:
model = Perceptron(eta = 0.5, epochs=10)
model.fit(X,y)

self.weights: [2.82396679e-05 1.93624813e-04 3.48482331e-05]
X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: 
[0 1 0 1]
error: 
0    0
1   -1
2    0
3    0
Name: y, dtype: int64
updated weights: 
[ 2.82396679e-05 -4.99806375e-01  5.00034848e-01]
#############

for epoch: 1
predicted value: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
[5.00028240e-01 1.93624813e-04 3.48482331e-05]
#############

for epoch: 2
predicted value: 
[0 1 1 1]
error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights: 
[ 2.82396679e-05 -4.99806375e-01  1.00003485e+00]
#############

for epoch: 3
predicted value: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights: 
[5.00028240e-01 1.93624813e-04 5.00034848e-01]
#############

for epoch: 4
predicted value: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[5.00028240e-01 1.9362481

## OR Gate Implementation

In [7]:
data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,1,1,1]}

OR = pd.DataFrame(data)
OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [8]:
X = OR.drop("y", axis=1)
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [9]:
y = OR['y']
y.to_frame()

y
0  0
1  1
2  1
3  1

In [10]:
model = Perceptron(eta = 0.5, epochs=10)
model.fit(X,y)

self.weights: [ 1.74553304e-04 -1.82823226e-05 -8.47930040e-06]
X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: 
[1 0 1 1]
error: 
0   -1
1    1
2    0
3    0
Name: y, dtype: int64
updated weights: 
[ 1.74553304e-04  4.99981718e-01 -8.47930040e-06]
#############

for epoch: 1
predicted value: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[1.74553304e-04 4.99981718e-01 4.99991521e-01]
#############

for epoch: 2
predicted value: 
[0 0 0 1]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights: 
[ 0.50017455  0.99998172 -0.50000848]
#############

for epoch: 3
predicted value: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[ 5.00174553e-01  9.99981718e-01 -8.47930040e-06]
#############

for epoch: 4
predicted value: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights: 
[0.50017455 0.99998172 0.499991

## XOR Gate - The Limitation

In [11]:
data = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,1,1,0]}

XOR = pd.DataFrame(data)
XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [12]:
X = XOR.drop("y", axis=1) # axis = 1 >>> dropping across column
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [13]:
y = XOR['y']
y.to_frame()

y
0  0
1  1
2  1
3  0

In [14]:
model = Perceptron(eta = 0.5, epochs=50)
model.fit(X,y)

self.weights: [ 7.16013340e-05 -4.70247628e-05 -7.85412338e-05]
X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights: 
[-0.4999284  -0.50004702  0.99992146]
#############

for epoch: 1
predicted value: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights: 
[ 7.16013340e-05 -4.70247628e-05 -7.85412338e-05]
#############

for epoch: 2
predicted value: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights: 
[-0.4999284  -0.50004702  0.99992146]
#############

for epoch: 3
predicted value: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights: 
[ 7.16013340e-05 -4.70247628e-05 -7.85412338e-05]
#############

for epoch: 4
predicted value: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights: 
[-0.4999284  -0.50004702  0.99992146]
##

# Perceptron Practice & Concepts


---

## Q1. In one sentence, what problem does a perceptron solve?

**Answer:** একটি পারসেপট্রন মূলত **Linearly Separable** ডেটাসেটকে একটি সরলরেখার (Decision Boundary) মাধ্যমে দুটি আলাদা শ্রেণিতে বিভক্ত বা ক্লাসিফাই করার সমস্যা সমাধান করে।

---

## Q2. What are the three main components of a perceptron?

**Answer:** একটি পারসেপট্রনের তিনটি প্রধান উপাদান হলো:

1. **Weights & Bias:** যা ইনপুটের গুরুত্ব নির্ধারণ করে এবং ডিসিশন বাউন্ডারিকে (Decision Boundary) পজিশন করতে সাহায্য করে।

2. **Summation Function:** যেখানে ইনপুট এবং ওয়েটগুলোর গুণফল যোগ করা হয়:  
   $z = \sum w_i x_i + b$

3. **Activation Function:** যা যোগফলটিকে নির্দিষ্ট আউটপুটে (যেমন: ০ বা ১) রূপান্তর করে। সাধারণত এখানে **Step Function** ব্যবহার করা হয়।



---

## Q3. Is perceptron a classifier or a regressor? Explain briefly.

**Answer:** পারসেপট্রন মূলত একটি **Classifier (ক্লাসিফায়ার)**।

**ব্যাখ্যা:** এটি ইনপুট ডেটা গ্রহণ করে এবং সেটিকে নির্দিষ্ট ক্যাটাগরি বা ক্লাসে (যেমন: ০ অথবা ১) ভাগ করে। যেহেতু এটি একটি অ্যাক্টিভেশন ফাংশন ব্যবহার করে আউটপুটকে আলাদা আলাদা বা ডিসক্রিট মানে রূপান্তর করে, তাই এটি রিগ্রেশন না করে ক্লাসিফিকেশন সম্পন্ন করে।

---


---

## Q4. Why do we need to update weights in a perceptron?

**Answer:** পারসেপট্রন যখন কোনো ইনপুট ডেটা নিয়ে কাজ করে, তখন শুরুতে সে ভুল প্রেডিকশন করতে পারে। **Weight Update** করার মূল উদ্দেশ্য হলো মডেলের এই ভুল বা 'Error' কমানো। ওয়েট পরিবর্তনের মাধ্যমে পারসেপট্রন শিখতে পারে কোন ইনপুটটি আউটপুটের জন্য কতটা গুরুত্বপূর্ণ, যা তাকে সঠিক ডিসিশন বাউন্ডারি (Decision Boundary) তৈরি করতে সাহায্য করে।

---

## Q5. What happens if we never update the weights during training?

**Answer:** যদি আমরা ওয়েট আপডেট না করি, তবে মডেলটি কখনোই শিখতে পারবে না (No Learning)।
* মডেলটি শুরুতে যে র‍্যান্ডম (Random) ওয়েট নিয়ে শুরু করেছিল, সবসময় সেই অনুযায়ী আউটপুট দেবে।
* এর ফলে মডেলের একুরেসি বাড়বে না এবং এটি ভুল প্রেডিকশন করতেই থাকবে। সহজ কথায়, মডেলটি কেবল একটি স্থির বা অকেজো ফাংশন হিসেবে রয়ে যাবে।

---

## Q6. Which two quantities decide how much the weight changes?

**Answer:** ওয়েট কতটা পরিবর্তিত হবে তা মূলত দুটি প্রধান বিষয়ের ওপর নির্ভর করে:

1. **Learning Rate ($\eta$):** এটি একটি ছোট ধ্রুবক মান যা নির্ধারণ করে প্রতিটি পদক্ষেপে কত বড় পরিবর্তন হবে।
2. **Error (Target - Prediction):** একচুয়াল টার্গেট এবং মডেলের দেওয়া প্রেডিকশনের মধ্যে পার্থক্য যত বেশি হবে, ওয়েট পরিবর্তনের পরিমাণও তত বড় হবে। এছাড়া ইনপুটের মান ($x$) এই পরিবর্তনের মাত্রাকে প্রভাবিত করে।

**Weight Update Formula:** $\Delta w = \eta \times (y_{target} - y_{predicted}) \times x$

---

---

## Q7. What does the term (y − ŷ) represent in perceptron learning?

**Answer:** (y − ŷ) অংশটি মূলত **Error** বা ভুলকে রিপ্রেজেন্ট করে।
* এখানে **y** হলো একচুয়াল টার্গেট (Actual Label) এবং **ŷ** হলো মডেলের দেওয়া প্রেডিকশন (Predicted Label)।
* যদি দুটির মান সমান হয়, তবে বিয়োগফল ০ হয় (কোনো ভুল নেই)।
* আর যদি তারা আলাদা হয়, তবে এই বিয়োগফলটি নির্দেশ করে যে ওয়েট কতটুকু এবং কোন দিকে (Positive নাকি Negative) পরিবর্তন করতে হবে।

---

## Q8. If the prediction is correct, will weights change? Why?

**Answer:** না, যদি প্রেডিকশন সঠিক হয় তবে **weights পরিবর্তন হবে না।**

**কারণ:** পারসেপট্রনের ওয়েট আপডেট ফর্মুলা হলো:  
$\Delta w = \eta \times (y - ŷ) \times x$  
যখন প্রেডিকশন সঠিক হয়, তখন $y = ŷ$ হয়, যার ফলে $(y - ŷ) = 0$ হয়ে যায়। পুরো গুণফলটি ০ হয়ে যাওয়ার কারণে নতুন ওয়েট এবং পুরনো ওয়েট একই থাকে। অর্থাৎ, মডেল মনে করে এই ইনপুটের জন্য বর্তমান ওয়েটগুলো ঠিক আছে।

---

## Q9. What role does the learning rate (η) play intuitively?

**Answer:** ইনটুইটিভলি (সহজভাবে) চিন্তা করলে, **Learning Rate (η)** হলো মডেলের **"পদক্ষেপের আকার" (Step Size)**।

* এটি ঠিক করে দেয় মডেলটি তার ভুল থেকে কত দ্রুত শিখবে।
* যদি $\eta$ খুব বড় হয়, তবে মডেলটি খুব দ্রুত ওয়েট পরিবর্তন করবে, যা অনেকটা বড় বড় লাফ দিয়ে চলার মতো। এতে সঠিক গন্তব্য (Global Minima) পার হয়ে যাওয়ার ভয় থাকে।
* যদি $\eta$ খুব ছোট হয়, তবে মডেলটি খুব ছোট ছোট পা ফেলে এগোবে। এতে শিখতে অনেক বেশি সময় লাগবে, কিন্তু এটি খুব নিখুঁতভাবে লক্ষ্যে পৌঁছাতে পারে।



---

---

## Q10. Write the AND gate truth table.

**Answer:** AND গেটের ক্ষেত্রে আউটপুট কেবল তখনই ১ হয় যখন দুটি ইনপুটই ১ থাকে। নিচে এর ট্রুথ টেবিল দেওয়া হলো:

| Input 1 ($x_1$) | Input 2 ($x_2$) | Output ($y$) |
| :---: | :---: | :---: |
| 0 | 0 | 0 |
| 0 | 1 | 0 |
| 1 | 0 | 0 |
| 1 | 1 | 1 |

---

## Q11. Why is AND gate linearly separable?

**Answer:** AND গেটকে **Linearly Separable** বলা হয় কারণ এর আউটপুটগুলোকে একটি টু-ডাইমেনশনাল (2D) গ্রাফে প্লট করলে দেখা যায় যে, '০' আউটপুট যুক্ত পয়েন্ট এবং '১' আউটপুট যুক্ত পয়েন্টকে একটি মাত্র সরলরেখা টেনে সম্পূর্ণ আলাদা করা সম্ভব। যে সকল ডেটাসেটকে একটি সরলরেখা (বা ডিসিশন বাউন্ডারি) দিয়ে বিভক্ত করা যায়, তারাই লিনিয়ারলি সেপারেবল।



---

## Q12. Draw a rough decision boundary that separates AND gate outputs.

**Answer:** গাণিতিক বা গ্রাফিক্যাল ভিউতে চিন্তা করলে, আমরা যদি একটি গ্রাফে $x_1$ এবং $x_2$ অক্ষ নেই:
* $(0,0), (0,1),$ এবং $(1,0)$ পয়েন্টগুলোতে আউটপুট **০**।
* কেবল $(1,1)$ পয়েন্টে আউটপুট **১**।

একটি সরলরেখা এমনভাবে টানা সম্ভব যা $(1,1)$ পয়েন্টটিকে একদিকে রাখবে এবং বাকি তিনটি পয়েন্টকে অন্যদিকে রাখবে। তোমার কোড ট্রেইনিং হওয়ার পর ঠিক এই রেখাটিই (Decision Boundary) খুঁজে বের করে।



---

---

## Q13. Why do we add a bias term in the perceptron?

**Answer:** বায়াস (Bias) মডেলটিকে এমন ফ্লেক্সিবিলিটি দেয় যাতে ডিসিশন বাউন্ডারিটি (Decision Boundary) মূলবিন্দু বা অরিজিন ($0,0$) দিয়ে না গিয়ে অন্য যেকোনো স্থান দিয়ে যেতে পারে।
* যদি বায়াস না থাকে, তবে সমীকরণটি হবে $y = w \cdot x$, যা সবসময় মূলবিন্দু দিয়ে যাবে।
* এর ফলে যদি সব ইনপুট $0$ হয়, তবে আউটপুট সবসময় $0$ আসবে। বায়াস যোগ করলে মডেলটি এই সীমাবদ্ধতা থেকে মুক্তি পায় এবং ডেটা অনুযায়ী সঠিক অবস্থানে রেখাটি স্থাপন করতে পারে।

---

## Q14. Why is bias often added after summation?

**Answer:** গাণিতিকভাবে বায়াসকে ইনপুট এবং ওয়েটের গুণফলের সাথে যোগ করা হয় কারণ এটি পুরো সমষ্টিকে (Summation) ডানে-বামে বা উপরে-নিচে শিফট করতে সাহায্য করে।
* এটি অনেকটা সরলরেখার সমীকরণ $y = mx + c$-এর ধ্রুবক 'c'-এর মতো কাজ করে। ইনপুটগুলোর প্রভাবে যে সমষ্টি পাওয়া যায়, তার সাথে বায়াস যোগ করলে নেট ইনপুট ($z$) এমন এক মানে পৌঁছায় যা অ্যাক্টিভেশন ফাংশন বা থ্রেশহোল্ড (Threshold) পার করতে সহায়ক হয়।



---

## Q15. Why do we initialize weights with small random values?

**Answer:** ওয়েট ইনিশিয়ালাইজেশনে ছোট র‍্যান্ডম মান ব্যবহারের পেছনে দুটি প্রধান কারণ আছে:

1. **Symmetry Breaking:** সব ওয়েট যদি একই মান (যেমন: ১ বা ০) দিয়ে শুরু হয়, তবে প্রতিটি নিউরন একই রকম আউটপুট দেবে এবং একই ভাবে আপডেট হবে। র‍্যান্ডম মান দিলে প্রতিটি ওয়েট আলাদা আলাদা ভাবে শিখতে পারে।
2. **Avoiding Saturation:** শুরুতে বড় মান দিলে অ্যাক্টিভেশন ফাংশনের আউটপুট খুব বড় হয়ে যেতে পারে, যা ট্রেইনিং প্রক্রিয়াকে জটিল করে তোলে। তোমার কোডে তুমি `1e-4` বা খুব ছোট মান ব্যবহার করেছ, যা মডেলকে স্থিরভাবে এবং নির্ভুলভাবে শিখতে সাহায্য করে।

---

---

## Q16. What is the purpose of np.dot(X, w) in perceptron code?

**Answer:** `np.dot(X, w)` এর কাজ হলো ইনপুট ফিচার ($X$) এবং তাদের সংশ্লিষ্ট ওয়েটগুলোর ($w$) **ডট প্রোডাক্ট (Dot Product)** বা লিনিয়ার কম্বিনেশন বের করা।
* এটি মূলত প্রতিটি ইনপুটকে তার ওয়েট দিয়ে গুণ করে যোগফল বের করে ($x_1w_1 + x_2w_2 + ... + x_nw_n$)।
* পারসেপট্রনের ডিসিশন বাউন্ডারি বা নেট ইনপুট ($z$) ক্যালকুলেট করার জন্য এটিই প্রধান গাণিতিক ধাপ।

---

## Q17. Why is matrix transpose used in weight updating?

**Answer:** ম্যাট্রিক্স ট্রান্সপোজ (Transpose) সাধারণত ডাইমেনশন বা আকার মেলানোর জন্য ব্যবহার করা হয়।
* যখন আমরা অনেকগুলো ডেটা পয়েন্ট নিয়ে কাজ করি, তখন ইনপুট ম্যাট্রিক্স $X$ এবং এরর (Error) ভেক্টরের আকার ভিন্ন হতে পারে।
* ওয়েট আপডেট করার সময় ম্যাট্রিক্স মাল্টিপ্লিকেশন সফল করতে ইনপুট ম্যাট্রিক্সকে ট্রান্সপোজ করতে হয়, যাতে আমরা প্রতিটি ইনপুটের জন্য তার সঠিক এরর অংশটুকু গুণ করতে পারি। এটি গাণিতিকভাবে নিশ্চিত করে যে আপডেটেড ওয়েট ভেক্টরটি আগের ওয়েট ভেক্টরের সমান আকৃতির হবে।

---

## Q18. What will happen if we remove the activation function?

**Answer:** যদি অ্যাক্টিভেশন ফাংশন সরিয়ে ফেলা হয়, তবে পারসেপট্রনটি আর ক্লাসিফায়ার থাকবে না; এটি একটি সাধারণ **Linear Regression** মডেলে পরিণত হবে।

**ফলাফল:**
1. মডেলটি কেবল কন্টিনিউয়াস (Continuous) ভ্যালু আউটপুট দেবে (যেমন: ২.৫, -১.৮ ইত্যাদি), কিন্তু সরাসরি '০' বা '১' ক্লাসে ভাগ করতে পারবে না।
2. কোনো থ্রেশহোল্ড (Threshold) না থাকায় মডেলটি সিদ্ধান্ত নিতে পারবে না যে কোন ইনপুটটি কোন ক্লাসের অন্তর্ভুক্ত।
3. জটিল প্যাটার্ন শেখার ক্ষমতা মডেলটি হারিয়ে ফেলবে।



---

---

## Q19. Why can OR gate be solved using a single perceptron?

**Answer:** OR গেটকে একটি সিঙ্গেল পারসেপট্রন দিয়ে সমাধান করা যায় কারণ এটি একটি **Linearly Separable** সমস্যা।
* OR গেটের ক্ষেত্রে ইনপুট (0,0)-এর জন্য আউটপুট ০, এবং বাকি সবক্ষেত্রে (0,1; 1,0; 1,1) আউটপুট ১।
* গ্রাফে এই পয়েন্টগুলো বসালে দেখা যায় যে, খুব সহজেই একটি সোজা রেখা টেনে (0,0) পয়েন্টটিকে অন্যান্য পয়েন্ট থেকে আলাদা করা সম্ভব। তাই পারসেপট্রন সহজেই এর জন্য সঠিক ওয়েট খুঁজে পায়।

---

## Q20. What is common between AND and OR gates from a geometry view?

**Answer:** জ্যামিতিক দৃষ্টিকোণ থেকে AND এবং OR গেটের মধ্যে প্রধান মিল হলো—উভয়েই **Linearly Separable**।
* অর্থাৎ, উভয়ের ক্ষেত্রেই একটি 2D প্লেনে আউটপুট ক্লাসগুলোকে (০ এবং ১) আলাদা করার জন্য একটি **সরলরেখা (Linear Decision Boundary)** যথেষ্ট।
* এদের ডেটা ডিস্ট্রিবিউশন এমন যে তারা কখনোই একে অপরকে "Cross" করে না বা এমন কোনো অবস্থানে থাকে না যেখানে বক্ররেখা (Non-linear curve) প্রয়োজন হয়।



---

## Q21. Does XOR need more features or more layers? Why?

**Answer:** XOR সমাধান করার জন্য সাধারণত **More Layers (হিডেন লেয়ার)** প্রয়োজন হয়, তবে চাইলে **More Features** দিয়েও এটি সমাধান করা সম্ভব।

* **More Layers (Multi-Layer Perceptron):** এটি সবচেয়ে জনপ্রিয় সমাধান। একাধিক লেয়ার বা নিউরন যোগ করলে নেটওয়ার্কটি নন-লিনিয়ার ডিসিশন বাউন্ডারি তৈরি করতে পারে, যা XOR-এর জটিল প্যাটার্ন বুঝতে সক্ষম।
* **More Features (Feature Engineering):** যদি আমরা ইনপুট হিসেবে $x_1$ এবং $x_2$-এর পাশাপাশি তাদের গুণফল ($x_1 \times x_2$) বা অন্য কোনো উচ্চতর ডাইমেনশন (Higher dimension) যোগ করি, তবে একটি সিঙ্গেল পারসেপট্রনও মাঝে মাঝে XOR সমাধান করতে পারে। একে বলা হয় ফিচার স্পেস ট্রান্সফরমেশন।



---

---

## Q22. What does linearly separable mean?

**Answer:** **Linearly Separable** মানে হলো এমন একটি ডেটাসেট যেখানে ভিন্ন ভিন্ন ক্লাসের ডেটা পয়েন্টগুলোকে একটি মাত্র সরলরেখা (2D-তে) বা সমতল (3D-তে) দিয়ে সম্পূর্ণ আলাদা করা সম্ভব।
* উদাহরণস্বরূপ, AND এবং OR গেটের ক্ষেত্রে '০' এবং '১' আউটপুটগুলোকে একটি সোজা দাগ দিয়ে দুই ভাগে ভাগ করা যায়। তাই তারা লিনিয়ারলি সেপারেবল।



---

## Q23. Why can’t a single straight line separate XOR data?

**Answer:** XOR গেটের ডেটা ডিস্ট্রিবিউশনটি একটু ভিন্ন। এর ক্ষেত্রে:
* $(0,0)$ এবং $(1,1)$ পয়েন্টের আউটপুট হলো **০**।
* $(0,1)$ এবং $(1,0)$ পয়েন্টের আউটপুট হলো **১**।
যদি আমরা গ্রাফে এগুলো বসাই, তবে দেখব যে একই ক্লাসের পয়েন্টগুলো বিপরীত কোণায় (Diagonally opposite) অবস্থান করছে। তুমি যেদিক দিয়েই একটি সোজা দাগ টানো না কেন, কখনোই একপাশে কেবল '১' এবং অন্যপাশে কেবল '০' রাখতে পারবে না। এই কারণেই একটি একক সরলরেখা XOR ডেটাকে আলাদা করতে ব্যর্থ হয়।



---

## Q24. What change is required to solve XOR successfully?

**Answer:** XOR সমস্যাটি সমাধান করার জন্য প্রধানত দুটি উপায় আছে:

1.  **Multi-Layer Perceptron (MLP):** এটি সবচেয়ে কার্যকর পদ্ধতি। এখানে ইনপুট এবং আউটপুট লেয়ারের মাঝে এক বা একাধিক **Hidden Layer** যোগ করা হয়। এই হিডেন লেয়ারগুলো ডেটাকে এমনভাবে ট্রান্সফর্ম করে যা আউটপুট লেয়ারের জন্য লিনিয়ারলি সেপারেবল হয়ে যায়।
2.  **Feature Mapping:** ইনপুটগুলোকে উচ্চতর ডাইমেনশনে (Higher Dimension) নিয়ে যাওয়া। যেমন- ইনপুট হিসেবে কেবল $x_1, x_2$ না নিয়ে যদি $x_1^2$ বা $x_1 \times x_2$ এর মতো ফিচার যোগ করা হয়, তবে একটি সিঙ্গেল লেয়ার পারসেপট্রনও মাঝে মাঝে এটি সমাধান করতে পারে।



---

---

## Q25. List two strengths of a perceptron.

**Answer:** পারসেপট্রনের দুটি প্রধান শক্তিশালী দিক হলো:
1. **Simplicity & Efficiency:** এটি গঠনগতভাবে খুব সহজ এবং লিনিয়ারলি সেপারেবল ডেটার জন্য খুব দ্রুত কাজ করে। এটি কম্পিউটেশনাল রিসোর্স খুব কম ব্যবহার করে।
2. **Guaranteed Convergence:** যদি ডেটা লিনিয়ারলি সেপারেবল হয়, তবে পারসেপট্রন অবশ্যই একটি সঠিক ডিসিশন বাউন্ডারি খুঁজে পাবে (Perceptron Convergence Theorem)। এটি বাইনারি ক্লাসিফিকেশনের একদম মৌলিক ভিত্তি।

---

## Q26. List two limitations of a perceptron.

**Answer:** পারসেপট্রনের দুটি প্রধান সীমাবদ্ধতা হলো:
1. **Linear Limitation:** এটি কেবল সরলরেখা দিয়ে আলাদা করা যায় এমন সমস্যা সমাধান করতে পারে। বাস্তব জগতের বেশিরভাগ জটিল বা নন-লিনিয়ার (যেমন XOR) সমস্যা এটি সমাধান করতে পারে না।
2. **Hard Threshold:** এটি কেবল ০ বা ১ আউটপুট দেয়। এটি প্রেডিকশনের ক্ষেত্রে কোনো প্রবাবিলিটি (Probability) বা কতটুকু নিশ্চিত (Confidence score) তা জানাতে পারে না।



---

## Q27. When should we avoid using a single-layer perceptron?

**Answer:** নিচের পরিস্থিতিগুলোতে সিঙ্গেল-লেয়ার পারসেপট্রন ব্যবহার করা এড়িয়ে চলা উচিত:
1. **Non-linear Data:** যখন ইনপুট ডেটার প্যাটার্ন জটিল এবং একটি সোজা দাগ দিয়ে আলাদা করা অসম্ভব হয় (যেমন: Image Recognition বা Speech Processing)।
2. **Multi-class Classification:** যখন ডেটাকে দুইয়ের অধিক শ্রেণিতে (যেমন: ১০টি আলাদা ক্যাটাগরি) নিখুঁতভাবে ভাগ করার প্রয়োজন হয়।
3. **Continuous Output:** যদি আউটপুট হিসেবে কোনো নির্দিষ্ট সংখ্যা বা রেঞ্জ (Regression) প্রয়োজন হয়, তবে পারসেপট্রন ব্যবহার করা ঠিক নয়।

---